spring:
   profiles:
      active: dev
   datasource:
#      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/gzz?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      username: root
      password: root
   application:
      name: spring-boot-jdbc